package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table help_category
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class HelpCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.parent_category_id
     *
     * @mbggenerated
     */
    private Integer parentCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.id
     *
     * @return the value of help_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.id
     *
     * @param id the value for help_category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.name
     *
     * @return the value of help_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.name
     *
     * @param name the value for help_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.parent_category_id
     *
     * @return the value of help_category.parent_category_id
     *
     * @mbggenerated
     */
    public Integer getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.parent_category_id
     *
     * @param parentCategoryId the value for help_category.parent_category_id
     *
     * @mbggenerated
     */
    public void setParentCategoryId(Integer parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.url
     *
     * @return the value of help_category.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.url
     *
     * @param url the value for help_category.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}