package test.dao;

import java.util.List;
import test.model.HelpCategory;

public interface HelpCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbggenerated
     */
    int insert(HelpCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbggenerated
     */
    HelpCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbggenerated
     */
    List<HelpCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HelpCategory record);
}